### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by thehlopster** [p4xon/SyscallHook#2]
Windows 10 pro 1909 18363.657

Error: PAGE_FAULT_IN_NONPAGED_AREA

Minidump:
[021420-9500-01.zip](https://github.com/p4xon/SyscallHook/files/4206491/021420-9500-01.zip)

**Comment by vitri0l** [comment]
did you fixed it?

**Comment by vitri0l** [comment]
I guess the pointer to keQueryPerformanceCounter in "Syscall Hook.cpp" Line 86 is invalid. Do you know how to fix this?
